# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: container-test-wapp

on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest

    needs: build

    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_92b3938d985146b2a030f1f1c041844a }}
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'

# AUTO GENERATed


# name: Build and deploy container app to Azure Web App

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: 'ubuntu-latest'

#     steps:
#     - uses: actions/checkout@v2

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v2

#     - name: Log in to registry
#       uses: docker/login-action@v2
#       with:
#         registry: https://mcr.microsoft.com/
#         username: ${{ secrets.AzureAppService_ContainerUsername_97dcc2c7d1164d75933ad933de126944 }}
#         password: ${{ secrets.AzureAppService_ContainerPassword_37c4d3ca08794d5d9df4429b17c3d05a }}

#     - name: Build and push container image to registry
#       uses: docker/build-push-action@v3
#       with:
#         push: true
#         tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_97dcc2c7d1164d75933ad933de126944 }}/appsvc/staticsite:${{ github.sha }}
#         file: ./Dockerfile

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: 'production'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

#     steps:
#     - name: Deploy to Azure Web App
#       id: deploy-to-webapp
#       uses: azure/webapps-deploy@v2
#       with:
#         app-name: 'container-test-wapp'
#         slot-name: 'production'
#         publish-profile: ${{ secrets.AzureAppService_PublishProfile_92b3938d985146b2a030f1f1c041844a }}
#         images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_97dcc2c7d1164d75933ad933de126944 }}/appsvc/staticsite:${{ github.sha }}'